use_frameworks!

platform :ios, '10.0'

target 'XSpecialTextField_Example' do
  pod 'XSpecialTextField', :path => '../'

  target 'XSpecialTextField_Tests' do
    inherit! :search_paths

    
  end
end
